export const DAYS_OF_WEEK = [
  { value: "Monday", label: "Mon" },
  { value: "Tuesday", label: "Tue" },
  { value: "Wednesday", label: "Wed" },
  { value: "Thursday", label: "Thu" },
  { value: "Friday", label: "Fri" },
  { value: "Saturday", label: "Sat" },
  { value: "Sunday", label: "Sun" },
] as const;

export const SKILL_LEVELS = [
  { value: "BEGINNER", label: "Beginner" },
  { value: "INTERMEDIATE", label: "Intermediate" },
  { value: "ADVANCED", label: "Advanced" },
  { value: "COMPETITIVE", label: "Competitive" },
] as const;

export const ACQUISITION_OPTIONS = [
  { value: "FACEBOOK", label: "Facebook" },
  { value: "INSTAGRAM", label: "Instagram" },
  { value: "TIKTOK", label: "TikTok" },
  { value: "WEBSITE", label: "Website" },
  { value: "WORD_OF_MOUTH", label: "Word of Mouth" },
  { value: "LEISURE_CENTRE", label: "Leisure Centre" },
  { value: "SAW_SESSION", label: "Saw a Session Running" },
  { value: "THROUGH_COACH", label: "Through a Coach" },
  { value: "REFERRAL", label: "Referral Link / Code" },
  { value: "OTHER", label: "Other" },
] as const;

export const COUNTRY_DIAL_CODES = [
  { code: "+44",  label: "🇬🇧 +44  United Kingdom" },
  { code: "+1",   label: "🇺🇸 +1   United States" },
  { code: "+1",   label: "🇨🇦 +1   Canada" },
  { code: "+61",  label: "🇦🇺 +61  Australia" },
  { code: "+64",  label: "🇳🇿 +64  New Zealand" },
  { code: "+91",  label: "🇮🇳 +91  India" },
  { code: "+92",  label: "🇵🇰 +92  Pakistan" },
  { code: "+880", label: "🇧🇩 +880 Bangladesh" },
  { code: "+94",  label: "🇱🇰 +94  Sri Lanka" },
  { code: "+60",  label: "🇲🇾 +60  Malaysia" },
  { code: "+65",  label: "🇸🇬 +65  Singapore" },
  { code: "+63",  label: "🇵🇭 +63  Philippines" },
  { code: "+62",  label: "🇮🇩 +62  Indonesia" },
  { code: "+86",  label: "🇨🇳 +86  China" },
  { code: "+852", label: "🇭🇰 +852 Hong Kong" },
  { code: "+82",  label: "🇰🇷 +82  South Korea" },
  { code: "+81",  label: "🇯🇵 +81  Japan" },
  { code: "+971", label: "🇦🇪 +971 UAE" },
  { code: "+966", label: "🇸🇦 +966 Saudi Arabia" },
  { code: "+974", label: "🇶🇦 +974 Qatar" },
  { code: "+973", label: "🇧🇭 +973 Bahrain" },
  { code: "+968", label: "🇴🇲 +968 Oman" },
  { code: "+965", label: "🇰🇼 +965 Kuwait" },
  { code: "+20",  label: "🇪🇬 +20  Egypt" },
  { code: "+234", label: "🇳🇬 +234 Nigeria" },
  { code: "+27",  label: "🇿🇦 +27  South Africa" },
  { code: "+254", label: "🇰🇪 +254 Kenya" },
  { code: "+233", label: "🇬🇭 +233 Ghana" },
  { code: "+33",  label: "🇫🇷 +33  France" },
  { code: "+49",  label: "🇩🇪 +49  Germany" },
  { code: "+34",  label: "🇪🇸 +34  Spain" },
  { code: "+39",  label: "🇮🇹 +39  Italy" },
  { code: "+31",  label: "🇳🇱 +31  Netherlands" },
  { code: "+32",  label: "🇧🇪 +32  Belgium" },
  { code: "+351", label: "🇵🇹 +351 Portugal" },
  { code: "+46",  label: "🇸🇪 +46  Sweden" },
  { code: "+47",  label: "🇳🇴 +47  Norway" },
  { code: "+45",  label: "🇩🇰 +45  Denmark" },
  { code: "+358", label: "🇫🇮 +358 Finland" },
  { code: "+48",  label: "🇵🇱 +48  Poland" },
  { code: "+55",  label: "🇧🇷 +55  Brazil" },
  { code: "+52",  label: "🇲🇽 +52  Mexico" },
] as const;
