services:
  app:
    build: .
    container_name: badminton-hub-app
    env_file: .env
    expose:
      - "5000"
    restart: unless-stopped

networks:
  default:
    external: true
    name: hub-network
