#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   bash deploy/mac/ssl-setup.sh
#
# Requires DOMAIN and LETSENCRYPT_EMAIL to be set in your .env file.
# Run this ONCE after docker:up to get a Let's Encrypt certificate and
# switch nginx to HTTPS. Re-run any time to renew manually.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"
COMPOSE_FILE="${PROJECT_ROOT}/docker-compose.yml"
TLS_CONF="${SCRIPT_DIR}/nginx/docker-tls.conf"
NGINX_CONF_LINE="./deploy/mac/nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro"
NGINX_TLS_LINE="./deploy/mac/nginx/docker-tls.conf:/etc/nginx/conf.d/default.conf:ro"

# ── Load env ──────────────────────────────────────────────────────────────────
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Missing .env at ${PROJECT_ROOT}/.env"
  exit 1
fi
set -a; source "${ENV_FILE}"; set +a

if [[ -z "${DOMAIN:-}" ]]; then
  echo "DOMAIN is not set in .env (e.g. DOMAIN=app.yourdomain.com)"
  exit 1
fi
if [[ -z "${LETSENCRYPT_EMAIL:-}" ]]; then
  echo "LETSENCRYPT_EMAIL is not set in .env (e.g. LETSENCRYPT_EMAIL=you@email.com)"
  exit 1
fi

cd "${PROJECT_ROOT}"

# ── Step 1: stop nginx to free port 80 for certbot standalone ─────────────────
echo "==> Step 1: Stopping nginx to free port 80 for certificate challenge..."
docker compose stop nginx || true

# ── Step 2: obtain certificate (standalone — certbot binds port 80 directly) ──
echo "==> Step 2: Obtaining Let's Encrypt certificate for ${DOMAIN}..."
docker compose --profile ssl run --rm -p 80:80 certbot certonly \
  --standalone \
  --email "${LETSENCRYPT_EMAIL}" \
  --agree-tos \
  --no-eff-email \
  -d "${DOMAIN}"

# ── Step 3: write TLS nginx config ───────────────────────────────────────────
echo "==> Step 3: Writing TLS nginx config..."
cat > "${TLS_CONF}" << EOF
# Generated by ssl-setup.sh — do not edit manually, re-run the script to regenerate.

server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_ciphers               ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       1d;

    add_header Strict-Transport-Security "max-age=63072000" always;

    client_max_body_size 10m;

    location / {
        proxy_pass http://app:5000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
EOF
echo "    Written: ${TLS_CONF}"

# ── Step 4: switch nginx to TLS config ───────────────────────────────────────
echo "==> Step 4: Switching nginx to TLS config..."
# Update docker-compose.yml nginx volume mount (HTTP → TLS config)
if grep -qF "${NGINX_CONF_LINE}" "${COMPOSE_FILE}"; then
  sed -i '' "s|${NGINX_CONF_LINE}|${NGINX_TLS_LINE}|g" "${COMPOSE_FILE}"
  echo "    docker-compose.yml updated."
elif grep -qF "${NGINX_TLS_LINE}" "${COMPOSE_FILE}"; then
  echo "    docker-compose.yml already using TLS config."
else
  echo "    WARNING: Could not auto-update docker-compose.yml."
  echo "    Manually change the nginx volume to: ${NGINX_TLS_LINE}"
fi

# ── Step 5: reload nginx ──────────────────────────────────────────────────────
echo "==> Step 5: Reloading nginx..."
docker compose up -d --no-deps nginx

echo ""
echo "TLS setup complete! Your app is now available at:"
echo "  https://${DOMAIN}"
echo ""
echo "Certificates auto-renew via certbot. To renew manually:"
echo "  bash deploy/mac/ssl-setup.sh"
