uploads = []
generated = []

[[outputs]]
id = "_DTq5o-onEE6_4AMQp_uJ"
uri = "file://Smart-Match-Engine-Algorithm.md"
type = "text"
title = "Smart Match Engine Algorithm (.md - formatted markdown)"

[[outputs]]
id = "KrpF-sIa-Tss54kBIBqTH"
uri = "file://Smart-Match-Engine-Algorithm.txt"
type = "text"
title = "Smart Match Engine Algorithm (.txt - plain text)"
