// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-banner/Current.tsx": () => import("../components/mockups/dashboard-banner/Current.tsx"),
  "./components/mockups/dashboard-banner/Premium.tsx": () => import("../components/mockups/dashboard-banner/Premium.tsx"),
  "./components/mockups/timeline-card/Current.tsx": () => import("../components/mockups/timeline-card/Current.tsx"),
  "./components/mockups/timeline-card/Premium.tsx": () => import("../components/mockups/timeline-card/Premium.tsx")
};
